### PR TITLE
PEP 8 issues resolved across static files.

### PR DESCRIPTION
**Pull request by MichaelChristenson**
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/flaskserver/5)

### CODE REVIEW

**Comment by christensonb** [comment]
Review status: 0 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[seaborn/flask_server/memcache.py, line 33 at r1](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-L2YfNwUvaJrG9ZShOs7:-L2YfNwUvaJrG9ZShOs8:b-d7pwzl) ([raw file](https://github.com/seaborngames/flaskserver/blob/0ba7113dad5d887b342489fbb455ed97c55146be/seaborn/flask_server/memcache.py#L33)):*
> ```Python
> 
>             if request_parameters:
>                 cache_key += ' '+\
> ```

bad break

---

*[seaborn/flask_server/blueprint/python_bindings/python_bindings.py, line 133 at r1](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-L2YfeBDCGsmNtR8OaZ-:-L2YfeBDCGsmNtR8OaZ0:bgjcx7v) ([raw file](https://github.com/seaborngames/flaskserver/blob/0ba7113dad5d887b342489fbb455ed97c55146be/seaborn/flask_server/blueprint/python_bindings/python_bindings.py#L133)):*
> ```Python
>     elif args:
>         ret += '%s%sdata=dict(%s))\n' % ("'%s'" % url,
>                                          tab, tab2.join(['%s=%s' % (arg, arg)\
> ```

bad break

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by christensonb** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by MichaelChristenson** [comment]
*[seaborn/flask_server/memcache.py, line 33 at r1](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-L2YfNwUvaJrG9ZShOs7:-L2bA9eaD46sF4HKjZ2t:b-2w8609) ([raw file](https://github.com/seaborngames/flaskserver/blob/0ba7113dad5d887b342489fbb455ed97c55146be/seaborn/flask_server/memcache.py#L33)):*
What of this?
> cache_key += ' '+' '.join([str(value) for key, value in sorted(request_parameters.items())])
cache_key += ' '+' '.join([str(value) 
                                        for key, value in sorted(request_parameters.items())])

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by MichaelChristenson** [comment]
*[seaborn/flask_server/blueprint/python_bindings/python_bindings.py, line 133 at r1](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-L2YfeBDCGsmNtR8OaZ-:-L2bAWtFOa7HKj09VvB2:b-8lvqgr) ([raw file](https://github.com/seaborngames/flaskserver/blob/0ba7113dad5d887b342489fbb455ed97c55146be/seaborn/flask_server/blueprint/python_bindings/python_bindings.py#L133)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

bad break
</blockquote></details>

What of after the first and third %'s?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by christensonb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[seaborn/flask_server/memcache.py, line 33 at r1](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-L2YfNwUvaJrG9ZShOs7:-L2kdCcNyPLTaeRfgzfY:b2yaask) ([raw file](https://github.com/seaborngames/flaskserver/blob/0ba7113dad5d887b342489fbb455ed97c55146be/seaborn/flask_server/memcache.py#L33)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

What of this?
> cache_key += ' '+' '.join([str(value) for key, value in sorted(request_parameters.items())])
cache_key += ' '+' '.join([str(value) 
                                        for key, value in sorted(request_parameters.items())])
</blockquote></details>

don't make the suggestion in comments, put it in the code

---

*[seaborn/flask_server/blueprint/python_bindings/python_bindings.py, line 133 at r1](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-L2YfeBDCGsmNtR8OaZ-:-L2kdK68oai6IkWim7nN:b-3mn41r) ([raw file](https://github.com/seaborngames/flaskserver/blob/0ba7113dad5d887b342489fbb455ed97c55146be/seaborn/flask_server/blueprint/python_bindings/python_bindings.py#L133)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

What of after the first and third %'s?
</blockquote></details>

put it in the code not comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by christensonb** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-:-L3ETCQ8xr3WumbdEGW0:bnfp4nl)*

**Comment by christensonb** [comment]
Reviewed 1 of 5 files at r2, 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by christensonb** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5)*

**Comment by christensonb** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/flaskserver/5#-:-L3PeYpR4b3H97sb4ww_:bnfp4nl)*

**Review by christensonb — APPROVED** [review]

**Pull request merged**
